In [16]:
#importar librerias o archivos
#Libreria para el comando del sistema
import os
#libreria para el manejo de datos como lo es pandas
import pandas as pd

# Importar archivos

In [17]:
#importar archivos 
data=pd.read_csv("Archivo1_Datos.csv",sep=";",encoding="latin-1")

In [18]:
#visualizacion de datos
data.head(5)#tail, las últimas filas de los datos

,orden_id,order_item_id,producto_id,vendedor_id,fecha_envio_limite,precio,valor_flete,codigo_postal_vendedor,ciudad_vendedor,departamento_vendedor,nombre_categoria_producto,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,peso_g_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
0,107500PO59A,A,PO59,VE5389,07/04/2018 18:12,271.86,30.72,52435,Mallama,Nariño,Productos ecoamigables,6,7,27,2486,17,11,14
1,37493PS22B,B,PS22,VE1558,20/10/2017 09:07,115.73,4.68,52203,Colon,Nariño,Carnicería,10,31,20,256,43,2,21
2,28050PK20B,B,PK20,VE9159,17/08/2017 08:15,432.99,82.70,66001,Pereira,Risaralda,Deportes,25,5,4,5270,9,27,29
3,52187PA10A,A,PA10,VE3159,23/09/2017 23:27,108.38,35.39,52435,Mallama,Nariño,Electrodomésticos,10,1,6,734,46,48,22
4,84639PR12A,A,PR12,VE5090,07/01/2018 11:50,51.50,11.10,73001,Ibague,Tolima,Frutas y verduras,23,16,35,884,45,26,18

In [19]:
#Revisar los tipos de datos en cada archivo
data.dtypes

orden_id                          object
order_item_id                     object
producto_id                       object
vendedor_id                       object
fecha_envio_limite                object
precio                           float64
valor_flete                      float64
codigo_postal_vendedor             int64
ciudad_vendedor                   object
departamento_vendedor             object
nombre_categoria_producto         object
longitud_nombre_producto           int64
longitud_descripcion_producto      int64
cantidad_fotos_producto            int64
peso_g_producto                    int64
longitud_cm_producto               int64
altura_cm_producto                 int64
ancho_cm_producto                  int64
dtype: object

# Generar tablas de frecuencia absoluta y relativa

In [20]:
#Tabla de frecuencias univariadas, comando para el uso de frecuencias absolutas
frec_data=data["nombre_categoria_producto"].value_counts().reset_index()
frec_data=frec_data.rename(columns={"count":"frecuencia_absoluta"}) #comando para cambiar el nombre de las columnas
frec_data.head(5)

  nombre_categoria_producto  frecuencia_absoluta
0                Tecnología                  543
1                  Deportes                  537
2         Frutas y verduras                  532
3                Carnicería                  523
4           Ropa de adultos                  521

In [21]:
#frecuencia relativa
frec_data["porcentaje_nombre_categoria_producto"]=frec_data["frecuencia_absoluta"].apply(lambda x: x/frec_data["frecuencia_absoluta"].sum())
frec_data.head(10)

,nombre_categoria_producto,frecuencia_absoluta,porcentaje_nombre_categoria_producto
0,Tecnología,543,0.053582
1,Deportes,537,0.052990
2,Frutas y verduras,532,0.052497
3,Carnicería,523,0.051608
4,Ropa de adultos,521,0.051411
5,Juguetes,519,0.051214
6,Ferretería,519,0.051214
7,Ropa infantil,512,0.050523
8,Electrodomésticos,510,0.050326
9,Dormitorio,509,0.050227

In [22]:
#Calculo para la frecuencia absoluta acumulada y relativa acumulada
#calculo de la frecuencia absoluta acumulada
frec_data["acumulada_nombre_categoria_producto"]=frec_data["frecuencia_absoluta"].cumsum()
frec_data["acumulada_porcentaje_nombre_categoria_producto"]=frec_data["porcentaje_nombre_categoria_producto"].cumsum()
frec_data.head(5)

,nombre_categoria_producto,frecuencia_absoluta,porcentaje_nombre_categoria_producto,acumulada_nombre_categoria_producto,acumulada_porcentaje_nombre_categoria_producto
0,Tecnología,543,0.053582,543,0.053582
1,Deportes,537,0.052990,1080,0.106572
2,Frutas y verduras,532,0.052497,1612,0.159068
3,Carnicería,523,0.051608,2135,0.210677
4,Ropa de adultos,521,0.051411,2656,0.262088

In [23]:
frec_data

,nombre_categoria_producto,frecuencia_absoluta,porcentaje_nombre_categoria_producto,acumulada_nombre_categoria_producto,acumulada_porcentaje_nombre_categoria_producto
0,Tecnología,543,0.053582,543,0.053582
1,Deportes,537,0.052990,1080,0.106572
2,Frutas y verduras,532,0.052497,1612,0.159068
3,Carnicería,523,0.051608,2135,0.210677
4,Ropa de adultos,521,0.051411,2656,0.262088
5,Juguetes,519,0.051214,3175,0.313302
6,Ferretería,519,0.051214,3694,0.364515
7,Ropa infantil,512,0.050523,4206,0.415038
8,Electrodomésticos,510,0.050326,4716,0.465364
9,Dormitorio,509,0.050227,5225,0.515591
10,Productos ecoamigables,501,0.049438,5726,0.565029
11,Lácteos,501,0.049438,6227,0.614466
12,Libros,499,0.049240,6726,0.663706
13,Tarjetas regalo,497,0.049043,7223,0.712749
14,Mascotas,496,0.048944,7719,0.761693
15,Salud,491,0.048451,8210,0.810144
16,Celulares,488,0.048155,8698,0.858299
17,Muebles,486,0.047957,9184,0.906256
18,Licor,475,0.046872,9659,0.953128
19,Bebés,475,0.046872,10134,1.000000

In [24]:
##Tabla de frecuenccia bivariada
#Tabla que muestra la frecuencia por ciudad de venta y categoría del producto 
pd.crosstab(index=data["nombre_categoria_producto"], columns=data["ciudad_vendedor"])

ciudad_vendedor,Abejorral,Abrego,Abriaqui,Acacias,Acandi,Acevedo,Achi,Agua de dios,Arauca,Arboleda,...,San andres,San jose del guaviare,San juan de arama,San juanito,Santa marta,Sincelejo,Tunja,Valledupar,Villavicencio,Yopal
nombre_categoria_producto,,,,,,,,,,,,,,,,,,,,,
Bebés,9,23,1,20,0,0,9,4,3,6,...,2,6,8,18,1,12,1,5,23,10
Carnicería,8,16,1,15,0,0,5,7,10,7,...,1,6,13,13,1,10,4,4,24,5
Celulares,7,19,0,17,0,1,11,9,4,9,...,3,3,11,12,0,8,2,5,17,16
Deportes,10,19,0,24,1,0,4,3,5,5,...,3,6,7,11,0,21,3,2,33,7
Dormitorio,8,9,2,19,0,0,9,3,11,9,...,2,6,9,10,1,17,2,2,31,7
Electrodomésticos,5,27,1,17,1,0,5,6,3,4,...,2,1,6,8,2,16,5,3,18,7
Ferretería,5,14,0,18,0,0,6,7,9,6,...,3,2,18,11,1,15,6,4,15,12
Frutas y verduras,6,20,0,16,2,0,6,5,8,12,...,2,7,15,16,2,14,2,1,24,15
Juguetes,9,18,0,19,2,0,11,3,6,11,...,6,1,15,11,3,17,4,3,30,12
Libros,7,18,1,20,2,0,9,9,5,8,...,1,1,15,11,2,10,4,3,22,13
Licor,6,16,0,14,0,1,10,4,9,2,...,1,6,9,18,1,19,3,6,22,10
Lácteos,6,12,1,19,0,3,10,8,7,6,...,1,5,12,11,1,14,4,4,11,16
Mascotas,9,12,0,13,1,0,7,7,4,7,...,4,7,15,14,2,11,1,8,19,17
Muebles,3,19,1,19,0,2,5,3,1,11,...,1,3,10,7,0,16,1,1,17,13
Productos ecoamigables,8,15,0,20,1,2,9,4,6,14,...,0,10,14,9,1,17,2,4,13,14
Ropa de adultos,4,20,1,20,1,0,11,3,3,10,...,2,7,17,15,0,15,4,2,14,6
Ropa infantil,12,22,2,15,0,2,11,3,11,11,...,1,4,14,18,3,9,3,3,20,10
Salud,5,16,1,11,0,0,6,4,10,3,...,1,2,14,14,1,18,5,4,19,13
Tarjetas regalo,9,20,1,21,1,0,9,5,13,4,...,5,5,13,11,2,15,2,2,13,11
Tecnología,8,20,2,20,1,1,6,4,3,8,...,0,4,13,10,3,15,4,6,20,10

# Medidas de tendencia Central

In [25]:
#Medidas de tendencia central 
#Media o promedio 
data["precio"].mean()

np.float64(119.7923465561476)

In [26]:
#medir la mediana
data["precio"].median()

83.12

In [27]:
#medir la moda
data["precio"].mode()

0     3.92
1    11.39
2    11.79
3    15.80
4    16.42
5    25.45
6    34.43
7    36.96
8    56.79
Name: precio, dtype: float64

# Medidas de localización

In [29]:
## Cuantiles 
#Calcular el 20%, 50% y 70 % del peso de los productos 
data["peso_g_producto"].quantile([0.20,0.50,0.70])

0.2     470.0
0.5    1458.5
0.7    2535.1
Name: peso_g_producto, dtype: float64

# Medidas de dispersión

In [30]:
#Encontrar la desviación estandar de la longitud de los productos 
#Muestras que tan lejo de la media se encuentran las observaciones 
data["longitud_cm_producto"].std()

15.292866357696994

In [31]:
#Rango intercualtil 
#Es la diferencia entre el tercer y el primer cuartil 
data["longitud_cm_producto"].quantile(0.75)-data["longitud_cm_producto"].quantile(0.25)

np.float64(22.0)

In [33]:
#Rango, representa la diferencia que existe la observación mas grande y la más pequeña 
data["longitud_cm_producto"].max()-data["longitud_cm_producto"].min()

91

In [34]:
#coeficiente de variación 
#Es la división de la desviación estandar sobre la media 
data["longitud_cm_producto"].std()/data["longitud_cm_producto"].mean()

np.float64(0.5085427931474799)

# BONUS

In [35]:
data.describe()

,precio,valor_flete,codigo_postal_vendedor,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,peso_g_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
count,10134.000000,10134.000000,10134.000000,10134.000000,10134.000000,10134.000000,10134.000000,10134.000000,10134.000000,10134.000000
mean,119.792347,20.053246,49991.684626,20.074798,19.845372,20.110026,2106.109236,30.071936,17.915433,22.905861
std,119.340785,20.106163,22463.895340,11.721956,11.854161,11.802456,2093.734472,15.292866,11.360360,11.151559
min,0.010000,0.000000,5001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,34.155000,5.760000,50001.000000,10.000000,10.000000,10.000000,607.000000,19.000000,9.000000,15.000000
50%,83.120000,13.980000,52323.000000,20.000000,20.000000,20.000000,1458.500000,30.000000,17.000000,23.000000
75%,165.515000,27.455000,54003.000000,30.000000,30.000000,30.000000,2941.000000,41.000000,26.000000,30.000000
max,1262.940000,183.150000,99001.000000,40.000000,40.000000,40.000000,20661.000000,91.000000,64.000000,72.000000

In [ ]:
data_filtrada = data[(data["Price"].notna()) & (data["price"] != 0)]